// Package localization holds the reference lists apps offer choices from:
// languages, countries and parental ratings.
package localization

import (
	_ "embed"
	"encoding/json"
	"strings"
	"sync"
)

// Language is an ISO 639-2 language.
type Language struct {
	// Name is the English name as the standard lists it ("Spanish;
	// Castilian").
	Name string
	// Bibliographic is the ISO 639-2/B code ("fre"), the code of languages
	// that have a single one.
	Bibliographic string
	// Terminology is the ISO 639-2/T code when it differs ("fra").
	Terminology string
	// Alpha2 is the ISO 639-1 code, for the languages that have one ("fr").
	Alpha2 string
}

// languagesJSON is generated by scripts/localization-data.sh from the
// Library of Congress's ISO 639-2 list.
//
//go:embed languages.json
var languagesJSON []byte

var languages = sync.OnceValue(func() []Language {
	var list []Language
	if err := json.Unmarshal(languagesJSON, &list); err != nil {
		panic("localization: embedded languages: " + err.Error())
	}
	return list
})

// codes maps every code of a language, in lower case, to its bibliographic
// code: "fre", "fra" and "fr" all give "fre".
var codes = sync.OnceValue(func() map[string]string {
	all := languages()
	index := make(map[string]string, 2*len(all))
	for _, language := range all {
		for _, code := range [...]string{language.Bibliographic, language.Terminology, language.Alpha2} {
			if code != "" {
				index[code] = language.Bibliographic
			}
		}
	}
	return index
})

// Languages returns the ISO 639-2 languages, sorted by English name. The
// list is shared: callers must not change it.
func Languages() []Language {
	return languages()
}

// Countries returns the ISO 3166-1 countries, sorted by English name. The
// list is shared: callers must not change it.
func Countries() []Country {
	return countries()
}

// LanguageCode returns the ISO 639-2/B code of a language given by any of
// its codes, in any letter case: "fra", "FRE" and "fr" all give "fre".
// Region subtags are ignored ("fr-CA" gives "fre"), and anything else is
// returned in lower case, so that two unknown tags still compare.
func LanguageCode(code string) string {
	code = strings.ToLower(strings.TrimSpace(code))
	if bibliographic, ok := codes()[code]; ok {
		return bibliographic
	}
	if base, _, cut := strings.Cut(strings.ReplaceAll(code, "_", "-"), "-"); cut {
		if bibliographic, ok := codes()[base]; ok {
			return bibliographic
		}
	}
	return code
}

// SameLanguage reports whether two codes name the same language, whichever
// of its ISO 639 codes each uses. An empty code matches nothing.
func SameLanguage(a, b string) bool {
	a, b = LanguageCode(a), LanguageCode(b)
	return a != "" && a == b
}
